In [8]:
import tensorflow as tf
import numpy as np

In [5]:
sentences = ["my name is kebing", "I don't like green onion", "I like ice cream"]

In [7]:
# max_tokens: maximum size of the vocabulary for this layer
tokenizer = tf.keras.layers.TextVectorization(max_tokens=10)
# computes a vocabulary of string terms from tokens in a datset
tokenizer.adapt(sentences)

In [14]:
tokenizer(sentences)

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[6, 5, 8, 7, 0],
       [3, 1, 2, 1, 4],
       [3, 2, 9, 1, 0]])>

In [17]:
# OOV is [UNK]
tokenizer("I like strawberries")

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 2, 1])>

In [16]:
tokenizer.get_vocabulary(include_special_tokens=True)

['', '[UNK]', 'like', 'i', 'onion', 'name', 'my', 'kebing', 'is', 'ice']